version: '3'
services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./back-end:/var/www/html
      - ./back-end/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - clm-network
  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: CLM_DB
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      # MYSQL_USER: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./back-end/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - clm-network

  webserver:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./back-end:/var/www/html
      - ./back-end/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - clm-network

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: frontend-clm
    networks:
      - clm-network
    env_file:
      - ./front-end/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  clm-network:
    driver: bridge

volumes:
  dbdata:
    driver: local